### ISSUE TITLE
Extraneous 64 in paths on 64bit arches

### ISSUE THREAD

**Issue by AdamMajer** [mheily/libkqueue#101]
@arr2036 I've noticed that https://github.com/mheily/libkqueue/commit/a1bd5e9c49af06fb319a58399470a47387c89edf adds an explicit 64 to the paths on 64-bit arches. Normally, the LIBDIR is already set to include the correct bits and hence the above commit ends up installing the library into /usr/lib6464

For reference, on openSUSE the standard %cmake rpm macro on x86 is (partially),

```
   /usr/bin/cmake $OLDPWD/. \
        -G"Unix Makefiles" \
        -DCMAKE_INSTALL_PREFIX:PATH=/usr \
        -DINCLUDE_INSTALL_DIR:PATH=/usr/include \
        -DLIB_INSTALL_DIR:PATH=/usr/lib64 \
        -DSYSCONF_INSTALL_DIR:PATH=/etc \
        -DSHARE_INSTALL_PREFIX:PATH=/usr/share \
        -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 \
...
```

**Comment by arr2036** [comment]
That change was made because cmake _wasn't_ previously doing that.  I guess this must have changed at some point in recent history.  Thinking about it more it does seem that omitting the '64' suffix was a bug on cmake's part.

**Comment by AdamMajer** [comment]
Thank you for the revert but it's not really cmake's job to determine the library layout. SUSE based distros, which is just a biarch, the `CMAKE_INSTALL_LIBDIR` is set to `/usr/lib64`. On Debian, which is multiarch layout, the install location would be set to `/usr/lib/x86_64-linux-gnu`. So the install location is really distribution specific.

But yes, the default install location should be correct too, and that's mostly a packaging bug for cmake.

**Comment by AdamMajer** [comment]
@arr2036 it's OK to close this :-) The revert fixes the problem with the double 64 in the path
