### ISSUE TITLE
MSVC support

### ISSUE THREAD

**Issue by Jan200101** [mheily/libkqueue#128]
At the moment libkqueue seems to target just MinGW, what is the stance on MSVC?

**Comment by arr2036** [comment]
Patches welcome? MSVC is supported explicitly by cmake.  If you get it building using MSVC and contribute back any build system fixes, code changes, and a CI job, we'd happily merge those changes in.

**Comment by Jan200101** [comment]
> Patches welcome? If you get it building using MSVC and contribute back any build system fixes, code changes, and a CI job, we'd happily merge those changes in.

Thats what I was looking for.
There are some projects out there that intentionally don't support MSVC so its better to ask first.
