### ISSUE TITLE
Missing support for macOS

### ISSUE THREAD

**Issue by barracuda156** [mheily/libkqueue#152]
Possible to add?

**Comment by jpereira** [comment]
@barracuda156 well, the `kqueue` is native for OSX as can be seen in https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/kqueue.2.html

**Comment by barracuda156** [comment]
Yes, it has some implementation, but incomplete on older systems. I am looking for a way to build `libdispatch` for PPC. Some of libdispatch implementations rely on kqueue. So far none worked :)

**Comment by arr2036** [comment]
The native kernel kqueue is more feature-full than libkqueue.  We have tests that run against libkqueue, FreeBSD and MacOS to ensure compatibility.  The native kqueue and libkqueue should have near identical APIs and ABIs, so you can simply build libdispatch against the native kqueue.  We will not be adding full support for macOS as there's very little sense in doing so beyond your use case of supporting PPC hardware.  If you require this functionality you should be able to implement it yourself as another platform in a fork of libkqueue.
