### ISSUE TITLE
Build failed under centos

### ISSUE THREAD

**Issue by weliu** [mheily/libkqueue#37]
```
[liuwf@localhost libkqueue-2.1.0]$ cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib ./
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_INSTALL_LIBDIR


-- Build files have been written to: /home/liuwf/workspace/2/trunk/usr/click/lib/libkqueue/libkqueue-2.1.0
[liuwf@localhost libkqueue-2.1.0]$ make
Scanning dependencies of target kqueue
[  7%] Building C object CMakeFiles/kqueue.dir/src/posix/platform.c.o
In file included from /home/liuwf/workspace/2/trunk/usr/click/lib/libkqueue/libkqueue-2.1.0/src/posix/platform.c:17:0:
/home/liuwf/workspace/2/trunk/usr/click/lib/libkqueue/libkqueue-2.1.0/src/posix/../common/private.h:23:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
make[2]: *** [CMakeFiles/kqueue.dir/src/posix/platform.c.o] Error 1
make[1]: *** [CMakeFiles/kqueue.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Mad-Onion** [comment]
I've got the same problem when I try to compile under SLES12 SP2
```
fooServer:/tmp/libkqueue-2.1.0 # make
Scanning dependencies of target kqueue
[  7%] Building C object CMakeFiles/kqueue.dir/src/posix/platform.c.o
In file included from /tmp/libkqueue-2.1.0/src/posix/platform.c:17:0:
/tmp/libkqueue-2.1.0/src/posix/../common/private.h:23:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
CMakeFiles/kqueue.dir/build.make:62: recipe for target 'CMakeFiles/kqueue.dir/src/posix/platform.c.o' failed
make[2]: *** [CMakeFiles/kqueue.dir/src/posix/platform.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/kqueue.dir/all' failed
make[1]: *** [CMakeFiles/kqueue.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by andruszd** [comment]
I get the same  error as Mad-Onion but on  opensuse tumbleweed   and using the following get errors about  adding AC_CONFIG_MACRO_DIRS([m4]) to configure.ac and  adding -I m4 to Makefile.am - if I do still get errors ,....

# Replace v2.1.0 with latest version
VERSION=2.1.0
wget https://github.com/mheily/libkqueue/archive/v${VERSION}.tar.gz
tar -xvzf v${VERSION}.tar.gz
cd ./libkqueue-${VERSION}
sed -ie "s/Version:.*/Version:    ${VERSION}/" ./libkqueue.spec
sed -ie "s/%{_mandir}\/man2\/kevent.2.*//" ./libkqueue.spec
sed -ie "s/^%{make_install}.*/%{make_install} \&\& rm -rf %{_libdir}\/*.a \&\& rm -rf %{_libdir}\/*.la/" ./libkqueue.spec
autoreconf -i
cd ..
tar -czf ./libkqueue-${VERSION}.tar.gz ./libkqueue-${VERSION}

# Only required if you don't already have a build environment setup
mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
cp ./libkqueue-${VERSION}.tar.gz ~/rpmbuild/SOURCES/libkqueue-${VERSION}.tar.gz
rpmbuild -ba ./libkqueue-${VERSION}/libkqueue.spec

**Comment by arr2036** [comment]
Could you verify this is still an issue with the current git head.  The examples you gave there are for the old build system.

**Comment by arr2036** [comment]
@weliu could you also try the current Git HEAD

**Comment by weliu** [comment]
@arr2036 It worked on current Git HEAD, and I used cmake3 in case of someone is interested.

[liuwf@localhost libkqueue]$ cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib ./
CMake Error at CMakeLists.txt:18 (cmake_minimum_required):
  CMake 3.4.3 or higher is required.  You are running version 2.8.11


-- Configuring incomplete, errors occurred!
[liuwf@localhost libkqueue]$ cmake3 -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib ./
-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Looking for include file sys/signalfd.h
-- Looking for include file sys/signalfd.h - found
-- Looking for include file sys/timerfd.h
-- Looking for include file sys/timerfd.h - found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - found
-- Looking for EPOLLRDHUP
-- Looking for EPOLLRDHUP - found
-- Looking for NOTE_TRUNCATE
-- Looking for NOTE_TRUNCATE - not found
-- Looking for ppoll
-- Looking for ppoll - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/liuwf/workspace/libkqueue
[liuwf@localhost libkqueue]$ make
Scanning dependencies of target kqueue
[  7%] Building C object CMakeFiles/kqueue.dir/src/common/filter.c.o
[ 14%] Building C object CMakeFiles/kqueue.dir/src/common/kevent.c.o
[ 21%] Building C object CMakeFiles/kqueue.dir/src/common/knote.c.o
[ 28%] Building C object CMakeFiles/kqueue.dir/src/common/kqueue.c.o
[ 35%] Building C object CMakeFiles/kqueue.dir/src/common/map.c.o
[ 42%] Building C object CMakeFiles/kqueue.dir/src/posix/platform.c.o
[ 50%] Building C object CMakeFiles/kqueue.dir/src/linux/platform.c.o
[ 57%] Building C object CMakeFiles/kqueue.dir/src/linux/read.c.o
[ 64%] Building C object CMakeFiles/kqueue.dir/src/linux/signal.c.o
[ 71%] Building C object CMakeFiles/kqueue.dir/src/linux/timer.c.o
[ 78%] Building C object CMakeFiles/kqueue.dir/src/linux/user.c.o
[ 85%] Building C object CMakeFiles/kqueue.dir/src/linux/vnode.c.o
[ 92%] Building C object CMakeFiles/kqueue.dir/src/linux/write.c.o
[100%] Linking C shared library libkqueue.so
[100%] Built target kqueue
