### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by marcos69** [mheily/libkqueue#5]
src/linux/read.c:207:74: error: comparison of constant 0 with boolean expression is always false
      [-Werror,-Wtautological-constant-out-of-range-compare]
    if ((kn->kn_flags & KNFL_REGULAR_FILE && kn->kdata.kn_eventfd != -1) < 0) {

**Comment by jemc** [comment]
@mheily - Can we get a release tag from latest master that includes this fix?

**Comment by mheily** [comment]
@jemc Sure, I just tagged v2.0.4 and released it.
