### ISSUE TITLE
please tag a new release!

### ISSUE THREAD

**Issue by CameronNemo** [mheily/libkqueue#51]
```
[ 14%] Building C object CMakeFiles/kqueue.dir/src/common/kevent.c.o
/builddir/libkqueue-2.2.0/src/common/kevent.c: In function 'kevent_dump':
/builddir/libkqueue-2.2.0/src/common/kevent.c:107:37: error: '%s' directive output may be truncated writing up to 1023 bytes into a region of size between 931 and 1004 [-Werror=format-truncation=]
/builddir/libkqueue-2.2.0/src/common/kevent.c:98:28:
     return ((const char *) &buf[0]);
                            ~~~~~~~   
/builddir/libkqueue-2.2.0/src/common/kevent.c:107:37:
             "{ ident=%d, filter=%s, %s, %s, data=%d, udata=%p }",
                                     ^~
/builddir/libkqueue-2.2.0/src/common/kevent.c:107:13: note: using the range [-2147483648, 2147483647] for directive argument
             "{ ident=%d, filter=%s, %s, %s, data=%d, udata=%p }",
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/kqueue.dir/build.make:76: CMakeFiles/kqueue.dir/src/common/kevent.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/kqueue.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

http://ix.io/1sfa

**Comment by CameronNemo** [comment]
note that this is the 2.2.0 release. tagging a release would be nice!

**Comment by arr2036** [comment]
I believe this was already fixed in HEAD, can you verify?

**Comment by CameronNemo** [comment]
It builds fine now, but there is no shared library object built... not sure what is going wrong.

**Comment by arr2036** [comment]
Hm, I've never had that problem.  Maybe ``git clean -fxd`` and try again?

**Comment by CameronNemo** [comment]
there is a `/usr/lib/libkqueue.so` but there is no version library. I have tried the build several times, each time redownloading HEAD.

**Comment by arr2036** [comment]
Then your previous statement was quite misleading.  You're welcome to investigate this yourself and submit a PR, but as the original issue has already been dealt with I'm going to close this ticket.

**Comment by CameronNemo** [comment]
The fix for the issue has yet to be released so I would still like to politely request a release.

As for the shared object issue, previous releases would produce a versioned and unversioned object. This is typical for a shared library.

https://packages.debian.org/sid/amd64/libkqueue0/filelist

https://packages.debian.org/sid/amd64/libkqueue-dev/filelist

when building the current HEAD, I am only noticing the files in the -dev package. The other package ends up with no files apart from the man page. This is an issue and I can file a new bug if you would like.
