### ISSUE TITLE
Versioned object not installed using cmake

### ISSUE THREAD

**Issue by CameronNemo** [mheily/libkqueue#52]
previous releases would produce a versioned and unversioned object. This is typical for a shared library.

https://packages.debian.org/sid/amd64/libkqueue0/filelist

https://packages.debian.org/sid/amd64/libkqueue-dev/filelist

when building the current HEAD, I am only noticing the files in the -dev package. The other package ends up with no files apart from the man page.

**Comment by arr2036** [comment]
Can you test the latest git HEAD?  The debian packages should now be versioned correctly.

**Comment by CameronNemo** [comment]
Seems all good.
