### ISSUE TITLE
Solaris Problem using your demo code !

### ISSUE THREAD

**Issue by fskale** [mheily/libkqueue#6]
I compiled the demo code (signal.c) and tried to test.
The test abort on line 202 src/solaris/platform.c

BT:

```
Core was generated by `./signal'.
Program terminated with signal SIGABRT, Aborted.
#0  0xfffffd7fff2ae7fa in _lwp_kill () from /lib/64/libc.so.1
(gdb) bt
Python Exception <type 'exceptions.ImportError'> No module named frames:
#0  0xfffffd7fff2ae7fa in _lwp_kill () from /lib/64/libc.so.1
#1  0xfffffd7fff2a50ff in thr_kill () from /lib/64/libc.so.1
#2  0xfffffd7fff243430 in raise () from /lib/64/libc.so.1
#3  0xfffffd7fff21d6c8 in abort () from /lib/64/libc.so.1
#4  0xfffffd7ffc519388 in solaris_kevent_copyout (kq=0x414270, nready=1, eventlist=0xfffffd7fffdffbc0, nevents=1) at src/solaris/platform.c:202
#5  0xfffffd7ffc517db4 in kevent (kqfd=3, changelist=0x0, nchanges=0, eventlist=0xfffffd7fffdffbc0, nevents=1, timeout=0xfffffd7fffdffbb0) at src/common/kevent.c:290
#6  0x0000000000401c76 in main () at signal.c:55
```

I read it will work on solaris, so please explain how to get things working on solaris.

Line 163 shows:
//XXX-FIXME WHAT ABOUT WRITE???
Please explain, because there's a socket.c but no write.c in src/solaris.
I manged to get the compile working be tweaking the GNUMakefile.
configure did no accept the --target switch for solaris.
Is this work in progress or should it work already ?

Rgds.

Franz

**Comment by mheily** [comment]
Sadly, with the demise of OpenSolaris, the licensing changes to Solaris, and the poor track record of Illumos-based distributions, I am no longer willing to spend my free time supporting libkqueue on Solaris. I am open to accepting outside contributions to fix Solaris support, but have not seen any interest in the last five years.
