### ISSUE TITLE
libpcap file descriptors no longer function

### ISSUE THREAD

**Issue by timwoj** [mheily/libkqueue#66]
I noticed that there was a PR (https://github.com/mheily/libkqueue/pull/33) a couple of years ago that fixed support for file descriptors for libpcap. It appears that somewhere in the intervening time, that support was broken again. When trying to run a simple application that tries to read from a libpcap FD, debug logging shows this:

```
KQ [26078]: linux_get_descriptor_type(): fd 6 is a socket
KQ [26078]: linux_get_descriptor_type(): unknown socket type: Bad file descriptor (errno=9)
```

libpcap file descriptors have a socket type of SOCK_RAW (3) which isn't currently being handled by this block: https://github.com/mheily/libkqueue/blob/master/src/linux/platform.c#L590-L656

**Comment by timwoj** [comment]
Here's a very simple test program that implements everything needed: https://gist.github.com/timwoj/3fb35ba61a67eeb9178393bf8518f841

You'll need to link against lpcap and change the interface name in the code. I tested this on macOS's version of kqueue and it works there.

**Comment by mheily** [comment]
Hi Tim,

Thanks for the bug report. I've created a pull request to add basic support for raw sockets. See pull request #67

**Comment by mheily** [comment]
I ran your test program using the code in the PR, and it appears to work. Here's the output:

```
 # LD_LIBRARY_PATH=. ./test-issue66                                    
Using pcap library libpcap version 1.8.1
Using fd 6
timeout
timeout
1 interfaces ready
packet of length 86
1 interfaces ready
packet of length 86
1 interfaces ready
packet of length 166
1 interfaces ready
packet of length 102
1 interfaces ready
packet of length 66
1 interfaces ready
packet of length 114
1 interfaces ready
packet of length 137
1 interfaces ready
packet of length 66
1 interfaces ready
packet of length 140
1 interfaces ready
packet of length 66
1 interfaces ready
packet of length 97
1 interfaces ready
packet of length 66
1 interfaces ready
packet of length 105
1 interfaces ready
packet of length 66
1 interfaces ready
packet of length 105
1 interfaces ready
packet of length 66
timeout
timeout
timeout
timeout
timeout
timeout
1 interfaces ready
packet of length 60
1 interfaces ready
packet of length 42
timeout
```

**Comment by mheily** [comment]
#67 has been merged, closing this.

**Comment by timwoj** [comment]
Amazing turnaround time, thank you!
