### ISSUE TITLE
Performance loss for always using high-res timers?

### ISSUE THREAD

**Issue by timwoj** [mheily/libkqueue#68]
Is there a significant performance loss for always using high-resolution timers under Linux? I'm using libkqueue on a project where timeouts are frequently sub-millisecond, but also often have decimal values where truncating to a millisecond would cause timing issues.

**Comment by arr2036** [comment]
Generally not, no.  Where in the code specifically is timer resolution being truncated?

**Comment by timwoj** [comment]
In `linux_kevent_wait`: https://github.com/mheily/libkqueue/blob/master/src/linux/platform.c#L402-L406

`epoll_wait` takes a timeout value in milliseconds, so any resolution finer than that gets chopped.

**Comment by arr2036** [comment]
There's code directly above that to handle high resolution timers: https://github.com/mheily/libkqueue/blob/master/src/linux/platform.c#L390

**Comment by timwoj** [comment]
I know, but only if the `ts` value is sub-millisecond as a whole. If it has `tv_sec` value at all, or if `tv_nsec` contains a millisecond component, then it will still call `epoll_wait` directly.

**Comment by arr2036** [comment]
I don't really see any issue removing the check for zero seconds... Can you try it out locally and if it works, send a PR?
