### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by timwoj** [mheily/libkqueue#96]
The last release was in Feb 2019. Any chance you guys can tag a new release with all of the changes since then?

**Comment by arr2036** [comment]
I'd support a new release.  There's one outstanding issue with EVFILT_READ / EVFILT_WRITE under linux documented here: https://github.com/mheily/libkqueue/issues/89

But I think that can wait until the next release.  I don't think many people will notice the problem, or at least far fewer people will notice this than would have noticed that you couldn't use concurrent read/write events for an FD.

**Comment by arr2036** [comment]
I think @mcnewton was adding libkqueue to our Jenkins instance too, so we may have more up to date packages coming soon, not dependent on Debian.  How's that going @mcnewton are they in a public repo yet?

**Comment by mcnewton** [comment]
Not in a public repo yet, I had to stop and move on to more pressing things temporarily. Debian packages are ready to go, think basic RPM packages are too (the cpack ones). Building packages from the source should be straightforward though, if needed.

**Comment by sethhall** [comment]
Any updates on this?

**Comment by arr2036** [comment]
@mheily would you mind tagging a new release?  Or giving me permission to tag releases on the repo.  Thanks!

**Comment by sethhall** [comment]
@mheily (just a ping for @arr2036's request)

**Comment by orbitz** [comment]
Any updates on this?

**Comment by mheily** [comment]
@arr2036 I am totally fine with you tagging new releases. If you are unable to do so, let me know.

**Comment by mheily** [comment]
I've tagged and released v2.4.0.
