### ISSUE TITLE
Different behavior in comparsion to FreeBSD (or undefined behavior)

### ISSUE THREAD

**Issue by Payne-X6** [mheily/libkqueue#99]
From FreeBSD manpage it seems like file descriptor should be removed from kqueue on close (which is by-the-way different behavior in comparsion to epoll, where underlying file descriptor has to be closed).

When I run small test code, it seems to fail with `libkqueue` and works on FreeBSD `kqueue`. I'm not sure it is undefined behavior of kqueue (implemented this way in FreeBSD) or bug on `libkqueue` side.

We are using `libkqueue-2.3.1` but it seems to be failing also on older versions.

_main.c_
```
// clang -Wall -lkqueue main.c

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <sys/event.h>
#include <sys/time.h>

#define PATTERN "42"

int main(void) {
	// Init kqueue
	int fd = kqueue();
	if (fd < 0) {
		return errno;
	}
	// Simulate client connection
	int channel[2];	
	int ret = pipe(channel);
	if (ret < 0) {
		close(fd);
		return errno;
	}
	// Setup and add event
	struct kevent events[1];
	EV_SET(events, channel[0], EVFILT_READ, EV_ADD, 0, 0, NULL);
	if (kevent(fd, events, sizeof(events)/sizeof(*events), NULL, 0, NULL) < 0) {
		close(channel[0]);
		close(channel[1]);
		close(fd);
		return errno;
	}
	// Duplicate recieve side of pipe
	int channel_dup = dup(channel[0]);
	if (channel_dup < 0) {
		close(channel[0]);
		close(channel[1]);
		close(fd);
		return EXIT_FAILURE;
	}
	// Close fd that is stored in the kqueue
	// Im not sure if it is UB, but as I understand it from FreeBSD man,
	// it should remove event from kqueue
	close(channel[0]);
	// Send data through pipe
	if (write(channel[1], &PATTERN, sizeof(PATTERN)) != sizeof(PATTERN)) {
		close(channel[1]);
		close(channel_dup);
		close(fd);
		return EXIT_FAILURE;
	}
	// Test if kqueue receive event (should not)
	struct kevent recv_event[sizeof(events)/sizeof(*events)];
	const struct timespec timeout = {
		.tv_sec = 0,
		.tv_nsec = 20
	};
	ret = kevent(fd, NULL, 0, recv_event, sizeof(recv_event)/sizeof(*recv_event), &timeout);
	if (ret == 0) {
		printf("Test success!\nEvent was removed from kqueue on close!\n");
	} else if (ret == 1) {
		printf("Test failed!\nEvent wasn't removed from kqueue on close!\n");
		ret = EXIT_SUCCESS;
	} else {
		ret = EXIT_FAILURE;
	}
	// Cleanup
	close(channel[1]);
	close(channel_dup);
	close(fd);
	// Should be clear
	return ret;
}
```

**Comment by orbitz** [comment]
@Payne-X6 According to FreeBSD manpage:

> Calling close() on a file descriptor will remove any kevents that reference the descriptor.

So what you're saying sounds right.  In this cod example, are you seeing "Test failed" because you're getting an event?

**Comment by orbitz** [comment]
Perhaps this is the case you're hitting in this example?

> Q6 Will closing a file descriptor cause it to be removed from all epoll sets automatically?

> A6 Yes, but be aware of the following point. A file descriptor is a reference to an open file description (see open(2)). Whenever a descriptor is duplicated via dup(2), dup2(2), fcntl(2) F_DUPFD, or fork(2), a new file descriptor referring to the same open file description is created. An open file description continues to exist until all file descriptors referring to it have been closed. A file descriptor is removed from an epoll set only after all the file descriptors referring to the underlying open file description have been closed (or before if the descriptor is explicitly removed using epoll_ctl(2) EPOLL_CTL_DEL). This means that even after a file descriptor that is part of an epoll set has been closed, events may be reported for that file descriptor if other file descriptors referring to the same underlying file description remain open.

**Comment by Payne-X6** [comment]
> @Payne-X6 According to FreeBSD manpage:
> 
> > Calling close() on a file descriptor will remove any kevents that reference the descriptor.
> 
> So what you're saying sounds right. In this cod example, are you seeing "Test failed" because you're getting an event?

Exactly, with `libkqueue` I get "Test failed" (because file descriptor is still in queue) and with the original `kqueue` the test passes.



> Perhaps this is the case you're hitting in this example?
> 
> > Q6 Will closing a file descriptor cause it to be removed from all epoll sets automatically?
> 
> > A6 Yes, but be aware of the following point. A file descriptor is a reference to an open file description (see open(2)). Whenever a descriptor is duplicated via dup(2), dup2(2), fcntl(2) F_DUPFD, or fork(2), a new file descriptor referring to the same open file description is created. An open file description continues to exist until all file descriptors referring to it have been closed. A file descriptor is removed from an epoll set only after all the file descriptors referring to the underlying open file description have been closed (or before if the descriptor is explicitly removed using epoll_ctl(2) EPOLL_CTL_DEL). This means that even after a file descriptor that is part of an epoll set has been closed, events may be reported for that file descriptor if other file descriptors referring to the same underlying file description remain open.

Yes, that's the way libkqueue behaves.

That quote sounds like an `epoll` man page. That's actually the main difference between epoll and kqueue API (as I understand it). From the `kqueue` man page:

`Calling close() on a file	descriptor will remove any kevents that reference the descriptor.`

[https://www.freebsd.org/cgi/man.cgi?query=kqueue&sektion=2](https://www.freebsd.org/cgi/man.cgi?query=kqueue&sektion=2)

**Comment by orbitz** [comment]
I've been investigating a bug in m ocaml bindings for libkqueue and I came across something related:

It looks libkqueue is tracking what filters have been added or removed via the its API.  And if you add the same filter multiple times, it only does it the first time presuming that the second filter is already being waited on.

But if you close an FD that you've added a filter for and then create a new FD that has the same value and try to add that filter, libkqueue will not know that it is not actually being tracked by the underlying epoll because it was closed, and thus it will not add it.

Has anyone else seen this?  I'm still figuring out the codebase so my analysis could be wrong.

**Comment by arr2036** [comment]
There's some issues which are not possible to fix with the current Linux APIs, and I believe this is one of them.   epoll will automatically remove the file descriptor from the interest list if it's closed.  There's no way that I know of, of getting a notification that a file descriptor has been closed, and thus no way to synchronise libkqueue's state.  You have to explicitly delete the file descriptor from the kqueue before closing the file descriptor.

**Comment by orbitz** [comment]
Is there a good place to document edge cases for developers?  At least it's an issue that can be worked around and the API returns a failure to the user, so it's not silent.

**Comment by arr2036** [comment]
I guess it'd be `BUGS`.
